services:

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: talkevents
      MYSQL_USER: bertolo
      MYSQL_PASSWORD: bertolo123
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local